name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run Cypress public homepage tests
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          spec: cypress/e2e/public/homepage/**/*.cy.js

        env:
          CYPRESS_adminUsername: ${{ secrets.CYPRESS_ADMIN_USERNAME }}
          CYPRESS_adminPassword: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}

      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports
          if-no-files-found: ignore
          retention-days: 2